# Generated by Django 4.2.1 on 2025-01-11 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('ProfilePicture', models.ImageField(null=True, upload_to='Image')),
                ('Address', models.CharField(max_length=200)),
                ('ustatus', models.CharField(default='pending', max_length=20)),
                ('logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('Experience', models.CharField(max_length=20)),
                ('ProfilePicture', models.ImageField(null=True, upload_to='Image')),
                ('Certificate', models.ImageField(null=True, upload_to='Image')),
                ('Address', models.CharField(max_length=200)),
                ('bstatus', models.CharField(default='pending', max_length=20)),
                ('logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
