# Generated by Django 4.2.1 on 2025-01-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0002_user_baker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baker',
            old_name='Address',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='baker',
            old_name='Email',
            new_name='Email1',
        ),
        migrations.RenameField(
            model_name='baker',
            old_name='Password',
            new_name='Password1',
        ),
        migrations.RenameField(
            model_name='baker',
            old_name='Phonenumber',
            new_name='Phonenumber1',
        ),
        migrations.RenameField(
            model_name='baker',
            old_name='ProfilePicture',
            new_name='ProfilePicture1',
        ),
        migrations.RenameField(
            model_name='baker',
            old_name='Username',
            new_name='Username1',
        ),
    ]
