# Generated by Django 4.2.1 on 2025-01-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_rename_address_baker_address1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CakeName', models.CharField(max_length=100)),
                ('CakeDescri', models.CharField(max_length=500)),
                ('CakeImage', models.ImageField(null=True, upload_to='Image')),
                ('CakeCategory', models.CharField(max_length=100)),
                ('CakePrice', models.IntegerField(null=True)),
                ('CakeWeight', models.CharField(max_length=200)),
                ('CakeFlavor', models.CharField(max_length=200)),
                ('CakeIngredients', models.CharField(max_length=500)),
                ('CustomizableOptions', models.CharField(max_length=500)),
                ('PreparationTime', models.CharField(max_length=500)),
                ('SpecialNotes', models.CharField(max_length=500)),
                ('Discount', models.CharField(max_length=500)),
                ('StockQuantity', models.CharField(max_length=500)),
                ('EarliestDelivery', models.CharField(default='Today', max_length=40)),
                ('cstatus', models.CharField(default='Available', max_length=40)),
                ('bakerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.baker')),
            ],
        ),
    ]
