# Generated by Django 4.2.1 on 2025-02-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0004_cakedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('deltime', models.CharField(max_length=500)),
                ('cakeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cakedetails')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.user')),
            ],
        ),
    ]
