# Generated by Django 4.2.1 on 2025-02-13 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('fstatus', models.CharField(default='pending', max_length=20)),
                ('cakeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cakedetails')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.user')),
            ],
        ),
    ]
