# Generated by Django 4.2.1 on 2025-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Rating',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
