# Generated by Django 5.2.7 on 2026-03-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0007_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakedetails',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='cakedetails',
            name='PreparationTime',
        ),
        migrations.RemoveField(
            model_name='cakedetails',
            name='SpecialNotes',
        ),
    ]
