# Generated by Django 5.2.7 on 2026-03-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0008_remove_cakedetails_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customization',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='bookingid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.booking'),
        ),
    ]
